package com.pe.aws.enterpriseti.entity;
// Generated 5/05/2020 03:53:40 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO", schema = "CDEVAWS")
public class Usuario implements java.io.Serializable {

	private Long usuarioId;
	private String usuarioAlias;
	private String usuarioDni;
	private String usuarioEmail;
	private String usuarioNames;
	private String usuarioPassword;

	public Usuario() {
	}

	public Usuario(Long usuarioId) {
		this.usuarioId = usuarioId;
	}

	public Usuario(Long usuarioId, String usuarioAlias, String usuarioDni, String usuarioEmail,
			String usuarioNames, String usuarioPassword) {
		this.usuarioId = usuarioId;
		this.usuarioAlias = usuarioAlias;
		this.usuarioDni = usuarioDni;
		this.usuarioEmail = usuarioEmail;
		this.usuarioNames = usuarioNames;
		this.usuarioPassword = usuarioPassword;
	}

	@Id
	@SequenceGenerator(name="USUARIO_SEQUENCE", sequenceName="usuario_seq")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="USUARIO_SEQUENCE")
	@Column(name = "USUARIO_ID", unique = true, nullable = false, scale = 0)
	public Long getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Long usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "USUARIO_ALIAS", length = 1020)
	public String getUsuarioAlias() {
		return this.usuarioAlias;
	}

	public void setUsuarioAlias(String usuarioAlias) {
		this.usuarioAlias = usuarioAlias;
	}

	@Column(name = "USUARIO_DNI", length = 1020)
	public String getUsuarioDni() {
		return this.usuarioDni;
	}

	public void setUsuarioDni(String usuarioDni) {
		this.usuarioDni = usuarioDni;
	}

	@Column(name = "USUARIO_EMAIL", length = 1020)
	public String getUsuarioEmail() {
		return this.usuarioEmail;
	}

	public void setUsuarioEmail(String usuarioEmail) {
		this.usuarioEmail = usuarioEmail;
	}

	@Column(name = "USUARIO_NAMES", length = 1020)
	public String getUsuarioNames() {
		return this.usuarioNames;
	}

	public void setUsuarioNames(String usuarioNames) {
		this.usuarioNames = usuarioNames;
	}

	@Column(name = "USUARIO_PASSWORD", length = 1020)
	public String getUsuarioPassword() {
		return this.usuarioPassword;
	}

	public void setUsuarioPassword(String usuarioPassword) {
		this.usuarioPassword = usuarioPassword;
	}

}
